services:
  nginx:
    image: nginx:alpine3.20
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx/conf/:/etc/nginx/conf.d/
      - ./docker/nginx/log/:/var/log/nginx/
      - ./app:/var/www
    depends_on:
      - php
      - db
    networks:
      - app_net

  php:
    build: docker/php/
    container_name: php
    ports:
      - 9000:9000
    volumes:
      - ./app:/var/www
    networks:
      - app_net

  db:
    image: postgres:alpine3.20
    container_name: db
    ports:
      - 5432:5432
    volumes:
      - dbstore:/var/lib/postgresql/
      - ./docker/db/log:/var/log/postgresql/
    networks:
      - app_net
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
         
networks:
  app_net:
    name: app_net_php

volumes:
  dbstore:
    name: ${DATABASE_VOLUME_NAME}
    